#!/usr/bin/env bash

set -eu

enviro="$XDG_SESSION_DESKTOP"

renameEnviro() { # $1 - name
    local rn
    case $enviro in
        "Hyprland")
            rn="hypr"
        ;;
        "scroll" | "Sway")
            rn="sway"
        ;;
        "niri")
            rn="niri"
        ;;
        *)
            notify-send "Unknown environment"
            exit 1
        ;;
    esac

    printf "$rn" # return renamed
}

resdir="$HOME/.local/share/ramwaybar"
generic_name="$(renameEnviro $enviro)"
enviro_dir="$resdir/environments"
config_base="$enviro_dir/base/config.jsonc"
modules_enviro="$enviro_dir/$generic_name/modules.jsonc"
config_enviro="$resdir/config/$generic_name/config.jsonc"

if [[ -d $(dirname $modules_enviro) ]]; then # checks if there is modules for this environment
    mkdir -p "$(dirname $config_enviro)"
    jq -rs 'add' <(sed 's|//.*||g' $modules_enviro) <(sed 's|//.*||g' $config_base) > $config_enviro
fi

waybar -c $config_enviro -s $resdir/style/catppuccin-mocha/style.css
